; Build all versions of CP/M-Plus *.SYS files
; Run DRI_CPM3.SUB to select Digital Research BDOS modules
; or USE_ZPM3.SUB for Simeon Cran's ZPM3 replacement BDOS
LDRBIOS.SUB
NBNKBIOS.SUB
BANKBIOS.SUB
;BNK1BIOS.SUB
BNK8BIOS.SUB
INT8BIOS.SUB
bigbios.sub
;
ERA GENCPM.DAT
ERA CONFIG.LIB
; Make *.SYS files loaders
SYSCOM.SUB
; Copy the compressed print file from RAMdisk
PIP C:=M:*.?Z?
; Create new CRC checksum file
ERA CRCKLIST.CRC
CRCK *.* F
; Done.
